/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import javax.swing.JOptionPane;

import Models.*;

@SuppressWarnings("serial")
public class Menu1 extends javax.swing.JFrame {
	
	private DataCSV csv = new DataCSV();
        

    public Menu1() {
        initComponents();
        setLocationRelativeTo(null);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        //jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        CadastroAluno = new javax.swing.JMenuItem();
        CadastroCurso = new javax.swing.JMenuItem();
        CadastroRendimento = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        Fechar1 = new javax.swing.JMenu();
        Fechar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);
        /*
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alves\\Pictures\\logo3.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-20, -10, 430, 330);
        */
        jMenu1.setText("Cadastro");

        CadastroAluno.setText("Aluno");
        CadastroAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroAlunoActionPerformed(evt);
            }
        });
        jMenu1.add(CadastroAluno);

        CadastroCurso.setText("Curso");
        CadastroCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroCursoActionPerformed(evt);
            }
        });
        jMenu1.add(CadastroCurso);

        CadastroRendimento.setText("Rendimento");
        CadastroRendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroRendimentoActionPerformed(evt);
            }
        });
        jMenu1.add(CadastroRendimento);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Listagem");

        jMenuItem4.setText("Cursos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Alunos");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Histórico");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Rendimento");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        Fechar1.setText("Sair");

        Fechar.setText("Fechar");
        Fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharActionPerformed(evt);
            }
        });
        Fechar1.add(Fechar);

        jMenuBar1.add(Fechar1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastroAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroAlunoActionPerformed
        CadastroAluno ca = new CadastroAluno();
        this.dispose();
    	ca.setVisible(true);
        
    	ca.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
            	csv.reload();
                Menu1.this.setVisible(true);
            }
        
        });
    }//GEN-LAST:event_CadastroAlunoActionPerformed
                                

    private void CadastroCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroCursoActionPerformed
        CadastroCurso cd = new CadastroCurso();
          this.dispose();
          cd.setVisible(true);
          
          
          cd.addWindowListener(new java.awt.event.WindowAdapter() {
              @Override
              public void windowClosed(java.awt.event.WindowEvent windowEvent) {
            	  csv.reload();
                  Menu1.this.setVisible(true);
              }
          });
    }//GEN-LAST:event_CadastroCursoActionPerformed
       
     
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        this.dispose();
        ListagemAlunos la = new ListagemAlunos(csv.getAlunosTable());
        la.setVisible(true);
        
        la.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                Menu1.this.setVisible(true);
            }
        });
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.dispose();
    	ListagemCursos lc = new ListagemCursos(csv.getCursosTable());
        lc.setVisible(true);
        
        
        lc.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                Menu1.this.setVisible(true);
            }
        });               
                        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        this.dispose();
        try {
	        ListagemHistorico lh = new ListagemHistorico();
	        lh.setVisible(true);
	        
	        lh.addWindowListener(new java.awt.event.WindowAdapter() {
	            @Override
	            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
	            	Menu1.this.setVisible(true);
	            }
	        });  
	    } catch(java.lang.IndexOutOfBoundsException e) {
	    	JOptionPane.showMessageDialog(null, "Cadastre ao menos um curso e um aluno antes de listar o histórico.");
	    	Menu1.this.setVisible(true);
	    } catch(java.lang.NullPointerException e) {
	    	JOptionPane.showMessageDialog(null, "Cadastre ao menos um curso e um aluno antes de listar o histórico.");
	    	Menu1.this.setVisible(true);
	    } 
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        this.dispose();
        try {
	        ListagemRendimento lr = new ListagemRendimento();
	        lr.setVisible(true);
	        lr.addWindowListener(new java.awt.event.WindowAdapter() {
	            @Override
	            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
	                Menu1.this.setVisible(true);
	            }
	        });  
	    } catch(java.lang.IndexOutOfBoundsException e) {
	    	JOptionPane.showMessageDialog(null, "Cadastre ao menos um curso antes de listar o rendimento.");
	    	Menu1.this.setVisible(true);
	    }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void CadastroRendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroRendimentoActionPerformed
        this.dispose();
        CadastroRendimento cr = new CadastroRendimento();
        cr.setVisible(true);
        cr.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {  
                Menu1.this.setVisible(true);
            }
        });      
    }//GEN-LAST:event_CadastroRendimentoActionPerformed

    private void FecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharActionPerformed
        this.csv.reload();
    	this.csv.saveAll();
    	System.exit(0);
    }//GEN-LAST:event_FecharActionPerformed
    
                                         

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu1().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadastroAluno;
    private javax.swing.JMenuItem CadastroCurso;
    private javax.swing.JMenuItem CadastroRendimento;
    private javax.swing.JMenuItem Fechar;
    private javax.swing.JMenu Fechar1;
    //private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
